# Generated by Django 4.0.4 on 2022-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynnegallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='location',
            new_name='location_name',
        ),
    ]
