# Generated by Django 4.0.4 on 2022-05-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynnegallery', '0002_rename_category_pictures_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='location_name',
            new_name='location',
        ),
    ]
