# Generated by Django 4.0.4 on 2022-05-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynnegallery', '0003_rename_category_name_pictures_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='category',
            new_name='pic_category',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='location',
            new_name='pic_location',
        ),
    ]
